name: Pull Request Develop 

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.0.2
      with:
        token: ${{ secrets.PAT }}
        commit-message: this is commit message
        committer: RoyLee-Opsv <roy.lee@opensurvey.co.kr>
        body: this is body
          next line
          new line
        title: this is title
        labels: this is label
        reviewers: opsvEdgar
        assignees: RoyLee-Opsv
        milestone: 2
        branch: develop
        draft: false


