name: Pull Request Develop 

on:
  workflow_dispatch:

jobs:
  createPullRequest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.0.2
      with:
        token: ${{ secrets.PAT }}
        commit-message: this is commit message
        body: this is body
          next line
          new line
        title: this is title
        labels: this is label


